version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting_app
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  voting-app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
